# Generated by Django 4.0.1 on 2022-02-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsstory_image_upload_alter_newsstory_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='image_upload',
            field=models.ImageField(blank=True, null=True, upload_to='news/static/news/images/'),
        ),
    ]
