# Generated by Django 4.0.1 on 2022-02-12 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_newsstory_image_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='image_upload',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
